<?php
'{"buff鸽":
    [
        {"员工":
            [
                {"buff":{"职务":"ceo","年龄":22,"住址":"光明小区"}},
                {"wuwei":{"职务":"cao","年龄":22,"住址":"红浪漫洗浴中心"}}
            ]
        },
        {"地址":"扬州市邗江路光明小区"},
        {"网址":
            {
                "官网":"www.buffge.com",
                "论坛":"bbs.buffge.com",
                "网站":"web.buffge.com",
                "游戏":"game.buffge.com"
            }
        }
    ]
}';

